version: '3'
services:
  web:
    image: dhis2/dhis2-web:trunk-tomcat7-jre8-latest
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - /home/ubuntu/ec2dhis2docker/includes/dhis.conf:/opt/dhis2/config/dhis.conf
      - /home/ubuntu/ec2dhis2docker/includes/server.xml:/usr/local/tomcat/conf/server.xml
    depends_on:
      - "db"
  db:
    image: mdillon/postgis
    command: "postgres -c max_locks_per_transaction=100"
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - /home/ubuntu/ec2dhis2docker/datadb:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: dhis2
      POSTGRES_USER: dhis
      POSTGRES_PASSWORD: dhis
